import '../public/css/global.css'
import ReduxProvider from '../redux'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <Toaster />
        <ReduxProvider>{children}</ReduxProvider>
        </body>
    </html>
  )
}
